### PR TITLE
Updated release notes for Harbor 1.8.2

### PR DESCRIPTION
**Pull request by stuclem**

### CODE REVIEW

**Comment by animatedmax** [comment]
Please do not merge until tile release.

**Comment by michmike** [comment]
/hold
@stuclem , it looks like there may be a need for more files to be updated. look at this PR for a list of files that need updating.
https://github.com/pivotal-cf/docs-vmware-harbor/pull/69/files

thanks!

**Comment by AndrewCovarruPivotal** [comment]
@stuclem Merged the PR. Thanks!

**Comment by stuclem** [comment]
> /hold
> @stuclem , it looks like there may be a need for more files to be updated. look at this PR for a list of files that need updating.
> https://github.com/pivotal-cf/docs-vmware-harbor/pull/69/files
> 
> thanks!

@michmike sorry for missing this. Updates are in new PR https://github.com/pivotal-cf/docs-vmware-harbor/pull/76.

**Pull request merged**
